global:
  domain: argocd.pollenjp.com # ingress

# redis-ha:
#   enabled: true

controller:
  replicas: 1

configs:
  params:
    server.insecure: true # ingress

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress: # ingress
    enabled: true
    ingressClassName: cilium
    tls: false
#  service: # argo-argocd-server
#    type: ClusterIP # service/argo-argocd-server

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2
