---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: postgres-pass
    literals:
      - password=password
configMapGenerator:
  - name: nginx-config-map
    files:
      - initdb.sql=initdb.sql
resources:
  - nginx-deployment.yaml
  - http-server-deployment.yaml
  - http-server-ingress.yaml
