name: Lint
on:
  push:
env:
  MISE_VERSION: 2025.8.4
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: ${{ env.MISE_VERSION }}
          install: true
          cache: true # [default: true] cache mise using GitHub's cache
          log_level: debug # [default: info] log level
          working_directory: .
      - run: mise run lint
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: ${{ env.MISE_VERSION }}
          install: true
          cache: true # [default: true] cache mise using GitHub's cache
          log_level: debug # [default: info] log level
          working_directory: .
      - run: mise run gen
